name: DevOps CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # 1. Chạy Unit Test để đảm bảo code không có bug logic
  test-logic:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: tododb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd backend && npm install

      - name: Initialize Database
        env:
          PGPASSWORD: 123456
        run: psql -h localhost -U postgres -d tododb -f database/database.sql

      - name: Run Unit Tests
        run: cd backend && npm test
        env:
          DB_HOST: localhost
          DB_PASSWORD: 123456
          DB_NAME: tododb
          NODE_ENV: test

  # 2. Build Docker Image và đẩy lên Docker Hub
  build-and-push:
    needs: test-logic
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

  # 3. Remote vào Server và cập nhật ứng dụng
  deploy-to-server:
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 1. Đi thẳng vào thư mục dự án đã xác định trên server
            cd /root/devops-project-hcm

            # 2. Lấy code mới nhất (file docker-compose.yml, v.v.)
            git pull origin main

            # 3. Đăng nhập Docker trên Server bằng Token
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            # 4. Kéo bản Image backend mới nhất về
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

            # 5. Restart hệ thống
            docker-compose down
            docker-compose up -d --build
